### ISSUE TITLE
Obsolete files in fracGC

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/pi-dual#3]
As far as I can tell, `C.agda` to `C4.agda` are all obsolete experiments, with all current content on `Comonadic` and `Comonadic2`.  If that is correct, can the obsolete stuff be deleted?  If there is stuff worth keeping/rescuing, can it be moved?

**Comment by sabry** [comment]
C3 is part of the story. Keep it please.



Sent from my Samsung Galaxy , an AT&T LTE smartphone


-------- Original message --------

**Comment by JacquesCarette** [comment]
Fixed by https://github.com/JacquesCarette/pi-dual/commit/3b4a962f595e9ada0ad461db0e0af8c186095e23
